---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# ggoxford

This is very much work in progress. I apologize for incomplete documentation.

## Installation

You can install ggoxford from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("schliebs/ggoxford")
```

## Example

This is a basic example of how to add country flags to bar plots:

```{r,message = F,warning = F}
library(tidyverse)
library(ggoxford)
library(ggtext)

wpop2013 <-
  tidyr::population %>%
  filter(year == 2013) %>%
  filter(population > 1e6) %>%
  mutate(iso3 = countrycode::countrycode(country,
                                         origin = "country.name.en",
                                         destination = "iso3c")
  ) 

head(wpop2013,10)
```

```{r,fig.width=10}
ggplot(data = wpop2013 %>%  slice(1:10),
       aes(x = iso3, y = population)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  geom_axis_flags(breaks = wpop2013$iso3,
                  labels = wpop2013$country,
                  country_icons = wpop2013$iso3,
                  width = 30,
                  lineheight = 2,
                  fontface = "bold"
                  )
```

Or with a few details added (now for the last 10 countries)

```{r,fig.width=10}

set.seed(123)

ggplot(data = wpop2013 %>% sample_n(10) ,
       aes(x = iso3, y = population)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = paste0(round(population/1e6),"m")),vjust = -0.25)+
  scale_y_continuous(breaks = seq(0e6,80e6,10e6),
                     labels = scales::comma(seq(0e6,80e6,10e6))) + 
  theme_minimal() +
  labs(x = NULL,y = "Population",title = "Population in 2013")+
  geom_axis_flags(breaks = wpop2013$iso3,
                  labels = wpop2013$country, 
                  country_icons = wpop2013$iso3,
                  width = 30,
                  lineheight = 2,
                  fontface = "bold"
                  )
```
